---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: jenkins-home-pvc
#    namespace: devel-pipe
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 3Gi
