---
  kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: jenkins-home-pv
#    namespace: devel-pipe
    labels:
      type: local
  spec:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    hostPath:
      path: "/data/jenkins"
#      path: '/Users/Shared/Jenkins/data'
