---
  apiVersion: v1
  kind: ReplicationController
  metadata:
    name: jenkins-rc
    labels:
      app: jenkins
  spec:
    replicas: 1
    selector:
      app: jenkins
    template:
      metadata:
        name: jenkins-rc
        labels:
          app: jenkins
      spec:
        containers:
        - name: jenkins
          image: magain/devel-pipe-jenkins:latest
          securityContext:
            privileged: true
          ports:
            - name: jnkns-ui-port
              containerPort: 8080
            - name: jnkns-jnlp-port
              containerPort: 50000
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-storage-graph
            - mountPath: /var/jenkins_home
              name: jenkins-data
        volumes:
          - name: docker-storage-graph
            emptyDir: {}
          - name: jenkins-data
            persistentVolumeClaim:
              claimName: jenkins-home-pvc
