---
  apiVersion: v1
  kind: ReplicationController
  metadata:
    name: jenkins-rc
#    namespace: devel-pipe
    labels:
      app: jenkins
  spec:
    replicas: 1
    selector:
      app: jenkins
    template:
      metadata:
        name: jenkins-rc
        labels:
          app: jenkins
      spec:
        privileged: true
        securityContext:
#          runAsUser: 1001
          fsGroup: 1000
        containers:
        - name: jenkins
          image: magain/devel-pipe-jenkins:latest
          ports:
            - name: jnkns-ui-port
              containerPort: 8080
            - name: jnkns-jnlp-port
              containerPort: 50000
          volumeMounts:
#            - mountPath: /var/run/docker.sock
#              name: docker-sock
            - mountPath: /var/jenkins_home
              name: jenkins-data
        volumes:
#          - name: docker-sock
#            hostPath:
#              path: /var/run/docker.sock
          - name: jenkins-data
#            hostPath:
#              path: '/Users/Shared/Jenkins/data'
            persistentVolumeClaim:
              claimName: jenkins-home-pvc
