---
  apiVersion: v1
  kind: Service
  metadata:
    name: jenkins-svc
#    namespace: devel-pipe
    labels:
      app: jenkins
  spec:
    selector:
      app: jenkins
    ports:
    - protocol: TCP
      port: 31001
      nodePort: 31001
      targetPort: jnkns-ui-port
    type: NodePort
